timeoutSecond: ${TIMEOUT_SECOND:180}
server:
  port: 8080
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway
  profiles:
    active: @profile@
  main:
    allow-bean-definition-overriding: true
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enable: true
    gateway:
      routes:
        - id: bds-user-doc
          order: 1
          predicates:
            - Path=/user/swagger-ui/**, /user/doc.html**, /user/v3/api-docs.yaml, /user/webjars/**, /user/v3/api-docs/**, /user/swagger-resources/**
          uri: lb://user-service
          filters:
            - OrderedAddRequestHeader=anonymous, TRUE
        - id: bds-user-login
          order: 2
          predicates:
            - Path=/user/user/anon/login,/user/user/anon/getAccessToken
          uri: lb://user-service
          filters:
            - name: CircuitBreaker
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - OrderedAddRequestHeader=anonymous, TRUE
        - id: bds-user-anonymous
          order: 5
          predicates:
            - Path=/user/*/anon/**
          uri: lb://user-service
          filters:
            - OrderedAddRequestHeader=anonymous, TRUE
        - id: bds-user
          order: 10
          predicates:
            - Path=/user/**
          uri: lb://user-service
          filters:
            - name: CircuitBreaker
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 30
                redis-rate-limiter.burstCapacity: 60
        - id: bds-bim-anonymous
          order: 20
          uri: lb://bimraw
          predicates:
            - Path=/BimRaw/OssMgt/**, /BimRaw/swagger**
          filters:
            - OrderedAddRequestHeader=anonymous, TRUE
        - id: bds-bim
          order: 25
          predicates:
            - Path=/BimRaw/**
          uri: lb://bimraw
          filters:
            - name: CircuitBreaker
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 30
                redis-rate-limiter.burstCapacity: 60
eureka: #eureka配置
  client:
    fetch-registry: true
    filter-only-up-instances: true
    register-with-eureka: ${REGISTER_EUREKA:true}
  instance:
    prefer-ip-address: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50
resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: ${TIMEOUT_SECOND:180s}
      cancelRunningFuture: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
    metrics:
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled: true
  endpoint:
    restart:
      enabled: true

