spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origin-patterns: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 18000
            exposed-headers:
              - Authorization
eureka: #eureka配置
  client:
    service-url:
      defaultZone: http://localhost:80/eureka,http://localhost:8761/eureka,http://localhost:8762/eureka


