server:
  port: 8069
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysqladm

